### ISSUE TITLE
Some problems about the paper

### ISSUE THREAD

**Issue by wangdeze18** [giganticode/probes#2]
Hello, I have read your article carefully. It is a very interesting work, but I still have some problems.

（1）May I ask which dataset does "the test dataset provided by Ahmad et al. (2021a) consisting of 10k examples of Java functions and methods" refer to?
  (2)  What do the abbreviations of the datasets in this repo represent and how they are constructed?

Thank you for your time in advance!

**Comment by wangdeze18** [comment]
Errors persists when loading pre-trained models CodeT5, PLBART-mtjava and PLBART-large....

**Comment by wangdeze18** [comment]
Sorry，I found that this bug was fixed when I upgraded transformer version to 4.17.0 or greater.

**Comment by anjandash** [comment]
Hi @wangdeze18 

Yes, now with the updated transformer package, you can work with CodeT5 and PLBART models.
As more new models are released, the transformer package needs to be updated from time to time. 

****

Regarding your other questions:

(1) 

Well, I do not follow your question about the dataset. Where do you find this statement: "the test dataset provided by Ahmad et al. (2021a) consisting of 10k examples of Java functions and methods"?

If it helps, our dataset is derived from the 50K-C dataset of compilable Java projects. 


(2) 

In the peer-reviewed version of the paper, the following 4 tasks were discussed: LEN, AST, CPX, TYP.
And you can find the task details and abbreviations in the [paper](https://arxiv.org/pdf/2108.11308.pdf). 

Since the publication of the paper, we have been working with a range of experimental tasks (perhaps the ones you see under the `data/` dir). These tasks are not ready at the moment, and only a handful of them will make the final cut, therefore I would be happy to share the details once the tasks have been finalized. 

****

I will close this issue here, but if you have more questions I'd be happy to address them. 
Please feel free to email me here: akarmakar@unibz.it
